config/routes.rb
Reporting::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :tickets, :except => ["new"] do
    match "/reopen" => "tickets#reopen", :via => "post", :as => "reopen"
    match "/close" => "tickets#close", :via => "post", :as => "close"

    resources :tracks, :only => ["create"]
  end

  resources :topics, :except => ["new", "show", "edit"]
  resources :subscribes, :only => ["create", "destroy"]

  #routes for subscribing topics
  get 'tickets/topics/:id' => "subscribes#topicShow", :as => "ticket_topic"
  get 'tickets/query/:query' => "tickets#query", :as => "ticket_query"

  #get resource for autocomplete
  get "/getUsers" => "autocomplete#getUsers"
  get "/getTopics" => "autocomplete#getTopics"
  get "/getTags" => "autocomplete#getTags"

  namespace :admin do
  	root :to => 'tickets#index'
  	resources :tickets
    resources :users, :only => ["index", "new", "create", "destroy"]
    
  end

  #mount Resque::Server.new, :at => "/resque" 


  root :to => "tickets#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :count, :name, :status, :color
  validates :name, :presence => true
  validates :name, :uniqueness => true
  
  has_many :tickets
  has_many :subscribes
  has_many :users, :through => :subscribes

  has_many :tracks
  
  def get_user_emails
  	
  	mails = []
  
  	self.subscribes.each do | s |
  		mails.push( s.user.email )
  	end
  	
  	mails
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topic = Topic.new
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { redirect_to topics_path }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to topics_path }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    
    if(@topic.destroy)
      @subscribes = Subscribe.where(["topic_id = ?", params[:id]])
      @subscribes.each do |subscribe|
        subscribe.destroy
      end

      Ticket.update_all( "topic_id = 0", ("topic_id = "+params[:id]) )
    end

    respond_to do |format|
      format.html { redirect_to topics_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<section id="topic-list">
  <div id="topic-box">
    <div class="box box-add">
      <%= form_for(@topic) do |f| %>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="40%"><%= f.text_field :color, :autocomplete => "off", :placeholder => "色碼 HEX 值" %></td>
          <td width="40%"><%= f.text_field :name, :autocomplete => "off", :placeholder => "專案名稱" %></td>
          <td width="20%"><a id="submitTopic" href="#">新增</a></td>
        </tr>
      </table>
      <% end %>
    </div>

    <% @topics.each do |topic| %>
    <div class="box">
      <div class="box-show">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td class="color"><a style="background:<%= topic.color %>">&nbsp;</a></td>
            <td class="name"><%= topic.name %></td>
            <td class="tool">
              <a href="#" class="edit" title="編輯"><img src="images/tool-2.png"></a>
              <%= link_to image_tag("/images/tool-1.png"), topic_path(topic), :class=> "delete", :method => "delete", :title => "刪除", data: { confirm: '確定刪除?' } %>
            </td>
          </tr>
        </table>
      </div>
      <!--box-show-->

      <div class="box-edit">
        <%= form_for(topic) do |f| %>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td class="color"><%= f.text_field :color, :autocomplete => "off", :placeholder => "色碼 HEX 值" %></td>
            <td class="name"><%= f.text_field :name, :autocomplete => "off", :placeholder => "專案名稱" %></td>
            <td class="tool"><a href="#" class="submit"><img src="images/tool-5.png"></a></td>
          </tr>
        </table>
        <% end %>
      </div>
      <!--box-edit--> 
    </div>
    <!--box-->
    <% end %>

  </div>
</section>

<script type="text/javascript">
$('#topic-list .box-edit').hide();
$('#topic-list .box-show .edit').click(function(){
  $(this).parents('.box').children('.box-edit').show();
  $(this).parents('.box').children('.box-show').hide();
  $('#topic-list .box-show .edit').unbind();
});

$("#submitTopic").click(function(){
  $("#new_topic").submit();
});
$(".submit").click(function(){
  $(this).parents("form:first").submit();
});
</script>