config/routes.rb
Reporting::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :tickets, :except => ["new"] do
    match "/reopen" => "tickets#reopen", :via => "post", :as => "reopen"
    match "/close" => "tickets#close", :via => "post", :as => "close"

    resources :tracks, :only => ["create"]
  end

  resources :topics, :except => ["new", "show", "edit"]
  resources :subscribes, :only => ["create", "destroy"]

  #routes for subscribing topics
  get 'tickets/topics/:id' => "subscribes#topicShow", :as => "ticket_topic"
  get 'tickets/query/:query' => "tickets#query", :as => "ticket_query"

  #get resource for autocomplete
  get "/getUsers" => "autocomplete#getUsers"
  get "/getTopics" => "autocomplete#getTopics"
  get "/getTags" => "autocomplete#getTags"

  namespace :admin do
  	root :to => 'tickets#index'
  	resources :tickets
    resources :users, :only => ["index", "new", "create", "destroy"]
    
  end

  #mount Resque::Server.new, :at => "/resque" 


  root :to => "tickets#index"

end

app/models/ticket.rb
# encoding: utf-8
class Ticket < ActiveRecord::Base
  attr_accessible :close_time, :deadline, :description, :period, :reporter, :status, :title, :topic_id, :treatment, :priority
  validates :description, :topic_id, :presence => true
  
  has_many :tracks, :dependent => :destroy
  belongs_to :topic, :counter_cache => :count
  belongs_to :user, :foreign_key => :reporter

  has_many :tickettags, :dependent => :destroy
  has_many :tags, :through => :tickettags
  
  after_create :init_track
  
  def init_track
  	self.newTrack('log', '建立於' + Time.now.to_date.to_s)
  end
  
  
  def newTrack(status, comment)
  
    track = self.tracks.new
    track.status = status
    track.actor = self.user.id
    track.comment = comment

    track.save
  end
  
  
end

app/controllers/tickets_controller.rb
# coding: utf-8
class TicketsController < ApplicationController
  before_filter :is_admin, :only => [:destroy]
  def index
    if(params[:order] == "createDESC")
      @tickets = Ticket.find(:all,
            :joins => "LEFT JOIN topics ON topics.id = tickets.topic_id LEFT JOIN users ON users.id = tickets.reporter" ,
            :select => "tickets.*, topics.name, topics.color, users.username",
            :order => "(case tickets.status
        when 'open' then 0
        else 1
        end),created_at ASC")
    elsif(params[:order] == "recent")
      @tickets = @recent
    elsif(params[:order] == "newtrack")
      @tickets = @newtrack
    else
      @tickets = Ticket.find(:all,
            :joins => "LEFT JOIN topics ON topics.id = tickets.topic_id LEFT JOIN users ON users.id = tickets.reporter" ,
            :select => "tickets.*, topics.name, topics.color, users.username",
            :order => "(case tickets.status
        when 'open' then 0
        else 1
        end),
        (case priority
        when 'high' then 0
        when 'medium' then 1
        when 'low' then 2
        else 3
        end), deadline ASC, created_at ASC")
    end
    @ticket = Ticket.new
    
  end

  def show
  	@ticket = Ticket.find(:first,
            :conditions => ["tickets.id = ?",params[:id] ],
            :joins => "LEFT JOIN topics ON topics.id = tickets.topic_id LEFT JOIN users ON users.id = tickets.reporter" ,
            :select => "tickets.*, topics.name, topics.color, users.username",
            :order => "created_at ASC")

    @track = Track.new
    @tracks = Track.find(:all,
            :conditions => ["tracks.ticket_id = ?",params[:id] ],
            :joins => "LEFT JOIN users ON users.id = tracks.actor" ,
            :select => "tracks.status, tracks.comment, tracks.created_at, users.username",
            :order => "tracks.created_at ASC")

  	respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def create
    @ticket = Ticket.new(params[:ticket])
    @ticket.reporter = current_user.id
    @ticket.cc = params[:cc].to_json
    @ticket.status = "open"

    respond_to do |format|
      if @ticket.save
        params[:tag] && params[:tag].each do |tag|
          @tickettag = Tickettag.new
          @tickettag.ticket_id = @ticket.id
          @tickettag.tag_id = tag

          @tickettag.save
        end

        params[:tagnew] && params[:tagnew].each do |tag|
          @tag = Tag.new
          @tag.name = tag

          if(@tag.save)
            @tickettag = Tickettag.new
            @tickettag.ticket_id = @ticket.id
            @tickettag.tag_id = @tag.id

            @tickettag.save
          end
        end

        format.html { redirect_to root_path, notice: 'ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { redirect_to root_path }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @ticket = Ticket.find(params[:id])

    if(!params[:ticket][:deadline].blank? && !(params[:ticket][:deadline] == (@ticket.deadline ? @ticket.deadline.strftime("%Y-%m-%d") : "")))
      newTrack("log", "將期限調整為："+params[:ticket][:deadline])
    end

    if(!params[:ticket][:period].blank? && !(params[:ticket][:period] == @ticket.period))
      newTrack("log", "修改了備註。")
    end

    if(@ticket.priority != params[:priority])
      case params[:priority]
      when "high"
        @priority = "緊急"
      when "medium"
        @priority = "普通"
      when "low"
        @priority = "暫緩"
      else
        @priority = "普通"
      end

      newTrack("log", "將優先權調整為："+@priority)
    end

    begin
      @ccOld = JSON.parse(@ticket.cc)
    rescue
      @ccOld = Array.new
    end

    @tagOld = Array.new
    @ticket.tags.each do |tag|
      @tagOld.push(tag.id.to_s)
    end

    @tagDelete = @tagOld - (params[:tag]||Array.new)
    @tagCreate = (params[:tag]||Array.new) - @tagOld

    if(@tagDelete.length > 0)
      @msg = "移除tag:"
      Tag.find_all_by_id(@tagDelete).each do |tag| 
        @msg = @msg+ " "+tag.name
      end
      newTrack("log", @msg)
    end

    if(@tagCreate.length > 0 || params[:tagnew])
      @msg = "新增tag:"
      Tag.find_all_by_id(@tagCreate).each do |tag|
        @msg = @msg+ " "+tag.name
      end

      params[:tagnew] && params[:tagnew].each do |tag|
        @msg = @msg+ " "+tag
      end
      newTrack("log", @msg)
    end

    
    @ccDelete = @ccOld - (params[:cc]||Array.new)
    @ccCreate = (params[:cc]||Array.new) - @ccOld

    if(@ccDelete.length > 0)
      @msg = "刪除標記"
      User.find_all_by_id(@ccDelete).each do |user| 
        @msg = @msg+ " "+user.username
      end
      newTrack("log", @msg)
    end

    if(@ccCreate.length > 0)
      @msg = "新增標記了"
      User.find_all_by_id(@ccCreate).each do |user|
        @msg = @msg+ " " + user.username
      end
      newTrack("log", @msg)
    end

    respond_to do |format|
      @ticket.cc = (params[:cc]||Array.new).to_json
      @ticket.priority = params[:priority]

      @tickettagDel = Tickettag.where(:ticket_id => @ticket.id).find_all_by_tag_id(@tagDelete)
      @tickettagDel.each do |tickettag|
        Tickettag.find(tickettag.id).delete
      end

      @tagCreate && @tagCreate.each do |tag|
        @tickettag = Tickettag.new
        @tickettag.ticket_id = @ticket.id
        @tickettag.tag_id = tag
        @tickettag.save
      end

      params[:tagnew] && params[:tagnew].each do |tag|
        @tag = Tag.new
        @tag.name = tag

        if(@tag.save)
          @tickettag = Tickettag.new
          @tickettag.ticket_id = @ticket.id
          @tickettag.tag_id = @tag.id

          @tickettag.save
        end
      end

      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to ticket_path(@ticket), notice: 'ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  def query
    @tickets = Ticket.find(:all,
            :conditions => ["description like ?","%"+ params[:query] + "%"],
            :joins => "LEFT JOIN topics ON topics.id = tickets.topic_id LEFT JOIN users ON users.id = tickets.reporter" ,
            :select => "tickets.*, topics.name, topics.color, users.username",
            :order => "created_at ASC")
  end

  def reopen
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.status = "open"
    @ticket.save

    newTrack("log", "重新開啟該回報。")

    respond_to do |format|
      format.html { redirect_to ticket_path(@ticket) }
      format.json { head :no_content }
    end
    
  end

  def close
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.status = "close"
    @ticket.save

    newTrack("log", "關閉該回報")

    newTrack("track", "關閉原因："+params[:track]["comment"]+"。")

    respond_to do |format|
      format.html { redirect_to ticket_path(@ticket) }
      format.json { head :no_content }
    end
  end

  def newTrack(status, comment)
    @track = @ticket.tracks.new
    @track.status = status
    @track.actor = current_user.id
    @track.comment = comment

    @track.save
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_listTickets.html.erb
<% @tickets.each do |ticket| %>
<div class="box<%= " highlight" if (ticket.priority == "high")%><%= " end" if (ticket.status == "close")%>" >
  <div class="avator">
    <div class="img-border"> <img src="/images/avator.jpg"> </div>
    <div class="name"><%= ticket.username %></div>
  </div>
  <!--avator-->
  <div class="content" data-redirect="<%= ticket_path(ticket) %>">
    <span class="time"><%= ticket.created_at.strftime("%Y-%m-%d %H:%M") %></span>
    <div class="text">
      <ul class="tag">
        <li class="tag-topic" style="background:<%= ticket.color ? ticket.color : '#7573FF' %>"><%= ticket.name ? ticket.name : "其他" %></li>
        <% ticket.tags.each do |tag| %>
        <li><%= tag.name %></li>
        <% end %>
      </ul>
      <!--tag-->
      <p><%= ticket.description %></p>
      <div class="cc"><% if ticket.cc != "null" && JSON.parse(ticket.cc).length>0 %>標記:
        <% User.find_all_by_id(JSON.parse(ticket.cc)).each do |cc| %>        
        <a href="#"><%= cc.username %></a>
        <% end %> 
        ，<% end %> 共有<a href="<%= ticket_path(ticket) %>"><%= ticket.tracks.count(:conditions => ["status = ?", "track"]) %></a>則<a href="<%= ticket_path(ticket) %>">留言</a></div>
    </div>
  </div>
  <!--content--> 
</div>
<!--box-->
<% end %>

<script type="text/javascript">
$("div.content").click(function(){
  window.location = $(this).data("redirect");
});
</script>

app/views/tickets/index.html.erb
<section id="msg-list">
  <%= form_for(@ticket) do |f| %>
  <section id="post">
    <div class="main">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="90%"><%= f.text_field :description, :id => "main-text", :autocomplete => "off" %></td>
          <td width="10%"><input type="button" id="main-send" value="送出"></td>
        </tr>
      </table>
    </div>

    <div class="option">
      <section class="tab-content">

        <div id="post-tag">

          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="topic" width="19%">
                <input type="text" id="ACTicketTopic" placeholder="專案名稱">
                <input type="text" id="ticketTopic" name="ticket[topic_id]" style="display:none;">
              </td>
              <td width="1%">&nbsp;</td>
              <td class="tagmod" width="80%">
                <input class="tagAC" type="text" name="tag[]" value="" />
              </td>
            </tr>
          </table>
        </div>

        <div id="post-cc">
          <div class="tagmod">
            <input class="userAC" type="text" name="cc[]" value="" />
          </div>
        </div>
        
        <div id="post-dl">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="date" width="19">
                <%= f.text_field :deadline, :placeholder => "選擇期限", :autocomplete => "off" %>
              </td>
              <td width="1%">&nbsp;</td>
              <td class="note" width="80%">
                <%= f.text_field :period, :placeholder => "備註欄", :autocomplete => "off" %>
              </td>
            </tr>
          </table>
        </div>
      </section>
      <!--tab-content-->
      <section class="tab">
        <ul>
          <li><a href="#post-tag"><img src="/images/post-tag.png"></a></li>
          <li><a href="#post-cc"><img src="/images/post-cc.png"></a></li>
          <li><a href="#post-dl"><img src="/images/post-dl.png"></a></li>
        </ul>
      </section>
      <!--tab-->
    </div>
    <!--option-->
  </section>
  <!--post-->
  <% end %>

  <%= render 'listTickets' %>

</section>
<script type="text/javascript">
$( "#ticket_deadline" ).datepicker();
$( "#ticket_deadline" ).change(function(){
  $(this).datepicker("option", "dateFormat", "yy-mm-dd");

  //compare the date
  if(new Date($(this).val()) <= new Date()){
    $(this).val("");
    alert("期限日期不能為過去的日期");
  }
});

$("#main-send").click(function(){
  $("#new_ticket").submit();
});
</script>

app/views/tickets/query.html.erb
<section id="msg-list">
	<% if @tickets.length>0 %>
	<%= render 'listTickets' %>
	<% else %>
	<p style="color:white;">找不到符合"<%= params[:query]%>"的問題記錄。</p>
	<% end %>
</section>

app/views/tickets/show.html.erb
<% if @ticket %>
<section id="original-po">
    <div class="tool">
        <% if @ticket.status == "close" %>
        <%= link_to image_tag("/images/tool-3.png"), ticket_reopen_path(@ticket), :method => "post", :id=> "on", :title => "開啟此回報" %>
        <% end %>

        <% if @ticket.status == "open" %>
        <a href="#" id="off" title="關閉此回報"><img src="/images/tool-4.png"></a>
        <a href="#" title="編輯" id="tool-edit"><img src="/images/tool-2.png"></a>
        <% end %>
        
        <%= link_to image_tag("/images/tool-1.png"), ticket_path(@ticket), :class=> "s-admin", :method => "delete", :title => "刪除" %>
    </div>

    <div class="box">
        <div class="avator">
            <div class="img-border"> <img src="/images/avator.jpg"> </div>
            <div class="name"><%= @ticket.username %></div>
        </div>
        <!--avator-->
        <div class="content">
            <div class="text">
                <ul class="tag">
                    <li class="tag-topic" style="background:<%= @ticket.color ? @ticket.color : '#7573FF' %>"><%= @ticket.name ? @ticket.name : "其他" %></li>
                    <% @ticket.tags.each do |tag| %>
                    <li><%= tag.name %></li>
                    <% end %>
                </ul>
                <p><%= @ticket.description %></p>
                <div class="cc"><% if @ticket.cc != "null" && JSON.parse(@ticket.cc).length>0 %>標記:
                    <% User.find_all_by_id(JSON.parse(@ticket.cc)).each do |cc| %>
                    <a href="#"><%= cc.username %></a>
                    <% end %>  ，<% end %>共有<a><%= @ticket.tracks.count(:conditions => ["status = ?", "track"]) %></a>則<a>留言</a>
                </div>
                <div class="deadline">期限至<a><%= @ticket.deadline && @ticket.deadline.strftime("%Y-%m-%d") %></a> ，<a><%= @ticket.period.length>0 ?  @ticket.period : "無備註" %></a></div>
            </div>
        </div>
        <!--content-->

        <div class="edit">
            <%= form_for(@ticket) do |f| %>
            <div class="text">
                <div class="tag">
                    <div class="tagmod">
                        <!--這裡放TAGMOD-->
                        <% @ticket.tags.each do |tag| %>
                        <input class="tagAC" type="text" name="tag[]" value='{"value": "<%= tag.name %>", "id": "<%= tag.id %>"}' />
                        <% end %>
                        <% if @ticket.tags.count == 0 %>
                        <input class="tagAC" type="text" name="tag[]" value='' />
                        <% end %>
                    </div>
                </div>
                <p><%= @ticket.description %></p>

                <div class="cc">
                    <div class="tagmod">
                        <!--這裡放TAGMOD-->
                        <% if @ticket.cc!="null" && JSON.parse(@ticket.cc).length>0 && JSON.parse(@ticket.cc)[0].length>0 %>
                        <% User.find_all_by_id(JSON.parse(@ticket.cc)).each do |cc| %>
                        <input class="userAC" type="text" name="cc[]" value='{"id": "<%= cc.id %>", "value": "<%= cc.username %>"}' />
                        <% end %>

                        <% else %>
                        <input class="userAC" type="text" name="cc[]" value='' />
                        <% end %>
                    </div>
                </div>

                <div class="deadline">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td class="date" width="19"><%= f.text_field :deadline, :placeholder => "選擇期限", :autocomplete => "off", :value => (@ticket.deadline.strftime("%Y-%m-%d") if @ticket.deadline) %></td>
                            <td width="1%">&nbsp;</td>
                            <td class="note" width="80%"><%= f.text_field :period, :placeholder => "備註欄", :autocomplete => "off" %></td>
                        </tr>
                    </table>
                </div>

                <div class="switch">
                    <input id="switch-low" name="priority" type="radio" value="low" <%= "checked" if(@ticket.priority=="low") %>>
                    <label for="switch-low" onclick="">暫緩</label>
                    <input id="switch-medium" name="priority" type="radio" value="medium" <%= "checked" if(@ticket.priority=="medium") %>>
                    <label for="switch-medium" onclick="">普通</label>
                    <input id="switch-high" name="priority" type="radio" value="high" <%= "checked" if(@ticket.priority=="high") %>>
                    <label for="switch-high" onclick="">緊急</label>
                    <span class="slide-button"><a>&nbsp;</a></span>
                </div>

                <div class="submit">
                    <a href="#" id = "editSubmit">送出</a>
                    <a href="#" id = "editCancel">取消</a>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <!--box-->
</section>
<!--original-po-->

<section id="msg-show">
	<% if @ticket.status == "open" %>
	<section id="post">
		<div class="main">
			<%= form_for(@track, :url => ticket_tracks_path(@ticket, @track)) do |f| %>
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="90%"><%= f.text_field :comment, :id => "main-text", :autocomplete => "off" %></td>
					<td width="10%"><input name="" type="button" id="main-send" value="送出"></td>
				</tr>
			</table>
			<% end %>
		</div>
		<div class="tips" style="display:none;">
          <p>請填寫關閉原因</p>
        </div>
	</section>
	<!--post-->
	<% end %>

    <% @tracks.each do |track| %>

	<% if track.status == "track" %>
	<div class="box">
		<div class="avator">
			<div class="img-border"> <img src="/images/avator.jpg"> </div>
			<div class="name"><%= track.username %></div>
		</div>
		<!--avator-->

		<div class="content"> <span class="time"><%= track.created_at %></span>
			<div class="text">
				<p><%= track.comment %></p>
			</div>
			<!--text-->
		</div>
		<!--content-->
	</div>
	<!--box-->
	<% end %>

	<% if track.status == "log" %>
	<div class="box log"> <span><a><%= track.username %></a><%= track.comment %></span> </div>
	<!--log-->
	<% end %>
	
	<% end %>


</section>
<!--mag-show-->


<script type="text/javascript">
$('.onoffswitch-checkbox').click(function(){
	$('.lock').delay(750).fadeOut(250)
})
$("#main-send").click(function(){
	$("#new_track").submit();
});

var btnOff = $("#off");
var btnOffCancel = $('<a href="#" id="offCancel" title="開啟此回報"><img src="/images/tool-3.png"></a>');
$("#off").click(function(){
	btnOffClick();
});

function btnOffClick(){
	$(".tips").show();
	if($("#offCancel").length==0){
		$("#off").after(btnOffCancel);
		$("#new_track").attr("action", "<%= ticket_close_path(@ticket) %>");

		btnOffCancel.click(function() {
			btnOffCancel.after(btnOff).remove();
			btnOff.bind("click", btnOffClick);
			$("#new_track").attr("action", "<%= ticket_tracks_path(@ticket) %>");
			$(".tips").hide();
		});
	}
	$("#off").remove();
}
$('#original-po .edit').hide()
 $('#original-po #tool-edit').click(function(){
  $('#original-po .edit').fadeIn(0)  
  $('#original-po .content').fadeOut(0) 
 })

$("#editCancel").click(function(){
	$('#original-po .edit').fadeOut(0)  
  $('#original-po .content').fadeIn(0) 	
});

$( "#ticket_deadline" ).datepicker();
$( "#ticket_deadline" ).change(function(){
  $(this).datepicker("option", "dateFormat", "yy-mm-dd");

  //compare the date
  if(new Date($(this).val()) <= new Date()){
    $(this).val('<%= @ticket.deadline.strftime("%Y-%m-%d") if @ticket.deadline %>');
    alert("期限日期不能為過去的日期");
  }
});

$("#editSubmit").click(function(){
	$("#edit_ticket_<%= @ticket.id%>").submit();
});
</script>
<% else %>
<script type="text/javascript">
window.location = "/";
</script>

<% end %>