config/routes.rb
Reporting::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :tickets, :except => ["new"] do
    match "/reopen" => "tickets#reopen", :via => "post", :as => "reopen"
    match "/close" => "tickets#close", :via => "post", :as => "close"

    resources :tracks, :only => ["create"]
  end

  resources :topics, :except => ["new", "show", "edit"]
  resources :subscribes, :only => ["create", "destroy"]

  #routes for subscribing topics
  get 'tickets/topics/:id' => "subscribes#topicShow", :as => "ticket_topic"
  get 'tickets/query/:query' => "tickets#query", :as => "ticket_query"

  #get resource for autocomplete
  get "/getUsers" => "autocomplete#getUsers"
  get "/getTopics" => "autocomplete#getTopics"
  get "/getTags" => "autocomplete#getTags"

  namespace :admin do
  	root :to => 'tickets#index'
  	resources :tickets
    resources :users, :only => ["index", "new", "create", "destroy"]
    
  end

  #mount Resque::Server.new, :at => "/resque" 


  root :to => "tickets#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :role
  validates_presence_of :username
  # attr_accessible :title, :body
  has_many :subscribes, :dependent => :destroy
  has_many :topics, :through => :subscribes

  has_many :tickets
  has_many :tracks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(params[:user])

		respond_to do |format|
			if(@user.save)
				format.html { redirect_to admin_users_path }
				format.json { render json: @user, status: :unprocessable_entity }
			else
				format.html { render "new" }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
	def destroy
		exit
		
	end
end

app/views/admin/users/index.html.erb
<section id="user-list">
	<div class="list">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<th class="avator">&nbsp;</th>
				<th class="name">名稱</th>
				<th class="userid" align="left">帳號</th>
				<th class="delete">刪除</th>
			</tr>
			<% @users.each do |user| %>
			<tr>
				<td align="center" class="avator"><img src="/images/avator.jpg"></td>
				<td align="center" class="name"><%= user.username %></td>
				<td class="userid"><%= user.email %></td>
				<td align="center"><a href="#"><img src="/images/tool-1.png"></a></td>
			</tr>
			<% end %>
		</table>
	</div>
	<div class="add"><a href="<%= new_admin_user_path %>"> 新增使用者</a></div>
</section>

app/views/admin/users/new.html.erb
<section id="user-edit">
  <%= form_for(@user, :url => admin_users_path) do |f| %>
  <div id="user-box">

    <div class="avator"> <a href="#">上傳圖片</a> <img src="/images/avator.jpg"> </div>
    <div class="form">
      <div class="text">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="30%" align="center">帳號</td>
            <td width="70%"><%= f.email_field :email, :autocomplete => "off" %></td>
          </tr>
        </table>
      </div>
      <div class="text">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="30%" align="center">名稱</td>
            <td width="70%"><%= f.text_field :username, :autocomplete => "off" %></td>
          </tr>
        </table>
      </div>
      <div class="text">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="30%" align="center">密碼</td>
            <td width="70%"><%= f.password_field :password, :autocomplete => "off" %></td>
          </tr>
        </table>
      </div>
      <div class="text">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="30%" align="center">確認密碼</td>
            <td width="70%"><%= f.password_field :password_confirmation %></td>
          </tr>
        </table>
      </div>
      <div class="submit"> <a href="<%= admin_users_path %>">取消</a><a href="#" id="submit-save">儲存</a> </div>
    </div>
    <!--form--> 
  </div>
  <% end %>
</section>
<script type="text/javascript">
$("#submit-save").click(function(){
  $("#new_user").submit();
});
</script>