config/routes.rb
Reporting::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  resources :tickets, :except => ["new"] do
    match "/reopen" => "tickets#reopen", :via => "post", :as => "reopen"
    match "/close" => "tickets#close", :via => "post", :as => "close"

    resources :tracks, :only => ["create"]
  end

  resources :topics, :except => ["new", "show", "edit"]
  resources :subscribes, :only => ["create", "destroy"]

  #routes for subscribing topics
  get 'tickets/topics/:id' => "subscribes#topicShow", :as => "ticket_topic"
  get 'tickets/query/:query' => "tickets#query", :as => "ticket_query"

  #get resource for autocomplete
  get "/getUsers" => "autocomplete#getUsers"
  get "/getTopics" => "autocomplete#getTopics"
  get "/getTags" => "autocomplete#getTags"

  namespace :admin do
  	root :to => 'tickets#index'
  	resources :tickets
    resources :users, :only => ["index", "new", "create", "destroy"]
    
  end

  #mount Resque::Server.new, :at => "/resque" 


  root :to => "tickets#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
  <meta name="Robots" content="index,follow"/>
  <meta http-equiv="content-language" content="zh-TW" />
  <title>夏天廣告回報系統</title>

  <link rel="StyleSheet" href="/plugin/tagit/css/jquery.tagedit.css" type="text/css" media="all"/>
  <link rel="stylesheet" href="/css/reset.css">
  <link rel="stylesheet" href="/css/default.css">
  <link rel="stylesheet" href="/css/aside.css">
  <link rel="stylesheet" media="screen and (max-width: 543px)" href="/css/mobile.css"/>
  <link rel="stylesheet" media="screen and (min-width: 544px) and (max-width: 896px)" href="/css/tablet.css" />
  <link rel="stylesheet" media="screen and (min-width: 897px)" href="/css/desktop.css"/>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <!--
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" media="screen and (max-width: 543px)" href="/assets/front/mobile"/>
  <link rel="stylesheet" media="screen and (min-width: 544px) and (max-width: 896px)" href="/assets/front/tablet" />
  <link rel="stylesheet" media="screen and (min-width: 897px)" href="/assets/front/desktop"/>
-->
  

  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="/plugin/tagit/js/jquery.autoGrowInput.js"></script>
  <script type="text/javascript" src="/plugin/tagit/js/jquery.tagedit.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <% if (user_signed_in?) %>
  <section id="wrapper">
    <aside>
      <section id="search">
        <div>
          <input type="text" id="search-text">
          <input type="button" id="search-button">
        </div>
      </section>
      <!--search-->

      <section id="info">
        <a id="info-edit" href="<%= edit_user_registration_path %>"><img src="/images/edit.png"></a>
        <div class="photo">
          <div class="img-border"><img src="/images/avator.jpg"></div>
        </div>
        <div id="account">
          <span class="name"><%= current_user.username %></span><br>
          <span class="email"><%= current_user.email %></span>
        </div>
      </section>
      <!--info-->

      <section id="topic">
        <h6>最新動態</h6>
        <div class="ticket">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="topic-name"><a href="/tickets?order=recent">近期回報</a></td>
              <td class="notice"><span><%= @recent.count %></span></td>
            </tr>
          </table>
        </div>

        <div class="ticket">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="topic-name"><a href="/tickets?order=newtrack">最新留言</a></td>
              <td class="notice"><span><%= @newtrack.count %></span></td>
            </tr>
          </table>
        </div>

        <div class="ticket">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="topic-name"><a href="/tickets">依優先排序</a></td>
              <td class="notice"></td>
            </tr>
          </table>
        </div>

        <div class="ticket">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="topic-name"><a href="/tickets?order=createDESC">依時間排序</a></td>
              <td class="notice"></td>
            </tr>
          </table>
        </div>

        <h6>我的訂閱
          <div class="tool"><a id="check-button">check</a><a id="del-button">delete</a><a id="add-button">Add</a></div>
        </h6>

        <div id="topic-add">
         <!-- -->
          <form accept-charset="UTF-8" action="/subscribes" method="post" id="topicForm" data-remote="true">
            <div style="margin:0;padding:0;display:inline">
              <input name="utf8" type="hidden" value="✓">
              <input name="authenticity_token" type="hidden" value="MtCsP1oggzzLksDJ4RZHdtPlEjiJNkbdDj3Gmmso15w=">
            </div>

            <input type="text" id="topic-text">
            <input name="topic" type="text" id="topic-value" style="display:none;">
            <input type="button" id="topic-button" value="增加">
          </form>
        </div>

        <% @subscribes.each do |subscribe| %>
        <div class="ticket" data-del="<%= subscribe.id %>">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td class="del"><%= link_to '', subscribe_path(subscribe), :method => :delete, :remote => true %></td>
              <td class="topic-name"><a href="<%= ticket_topic_path(subscribe.topic_id) %>"><%= subscribe.name %></a></td>
              <td class="notice"><% if subscribe.count>0 %><span><%= subscribe.count %></span><% end %></td>
            </tr>
          </table>
        </div>
        <% end %>
      </section>
      <!--topic-->
    </aside>

    <article>
      <header>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td id="aside-ctrl"><a href="#"><img src="/images/nav.png"></a></td>
            <td><h1><a href="/">夏天廣告回報系統</a></h1></td>
            <td class="tool">
              <a href="#" id="tool-ctrl"><img src="/images/set.png"></a>
              <div id="tool-list"><%= link_to (image_tag("/images/logout.png")+"登出"), destroy_user_session_path, method: :delete %> <%= link_to (image_tag("/images/tag.png")+"專案管理") ,topics_path %> <%= link_to (image_tag("/images/user.png")+"使用者列表") ,admin_users_path, :class => "s-admin" %></div>
            </td>
          </tr>
        </table>
      </header>

      <%= yield %>

    </article>
  </section>

  <% else %>

  <%= yield %>

  <% end %>
</body>

<script type="text/javascript">
/* search description from tickets */
$("#search-button").click(function(){
  var queryString = $("#search-text").val();
  if (queryString) {
    document.location.href = "/tickets/query/" + queryString;
  }
});
$("#search-text").keydown(function(event){
  if (event.keyCode == 13){
    $("#search-button").trigger('click');
  }
});


/* autocomplete : subscribing topic */
$.ajax({
  async: false,
  url: "/getTopics",
  dataType: 'json',
  complete: function (XMLHttpRequest, textStatus) {
    var topics = $.parseJSON(XMLHttpRequest.responseText);

    $("#topic-text").autocomplete({
      source: topics,
      minLength: 0,
      change: function (event, ui) { $("#topic-value").val(JSON.stringify(ui.item)); }
    })
    .focus(function() {
      $(this).autocomplete('search', $(this).val())
    })

    $("#ACTicketTopic").autocomplete({
      source: topics,
      minLength: 0,
      change: function (event, ui) {
        if ( !ui.item ) {
          for(var item in topics){
            if($(this).val() == topics[item].value)
            {
              $("#ticketTopic").val(topics[item].id); 
              break;
            }
            if(item == topics.length-1){
              alert("該專案不存在，請先新增新專案。");
              $(this).val("");
            }
          }

        }
        else{
          $("#ticketTopic").val(ui.item.id); 
        }

        
      }
    })
    .focus(function() {
      $(this).autocomplete('search', $(this).val())
    })
  }
});

/* autocomplete : new ticket */
$.ajax({
  async: false,
  url: "/getTags",
  dataType: 'json',
  complete: function (XMLHttpRequest, textStatus) {
    var tagList = $.parseJSON(XMLHttpRequest.responseText);

    $(".tagAC").tagedit({
      autocompleteURL: tagList,
      tagShowValue: false,
      allowEdit: false,
      texts: {
        recordChange: "#tagChange",
        removeLinkTitle: "",
        placeholder: "添加標籤"
      }
    });
  }
});
$.ajax({
  async: false,
  url: "/getUsers",
  dataType: 'json',
  complete: function (XMLHttpRequest, textStatus) {
    var ccList = $.parseJSON(XMLHttpRequest.responseText);

    $(".userAC").tagedit({
      autocompleteURL: ccList,
      allowEdit: false,
      allowSelfNew: false,
      texts: {
        recordChange: "#ccChange",
        removeLinkTitle: "",
        notInList: "請選擇清單中的使用者。",
        placeholder: "想要把誰標記進來？"
      }
    });
  }
});

/* new ticket */
$("#topic-button").click(function(){
  $("#topicForm").submit();
});

<% if flash[:IDnotice] %>
alert("<%= flash[:IDnotice] %>");
<% end %>

</script>

</html>